language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
  - "pypy"
  - "pypy3"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - sudo pip install -r https://raw.githubusercontent.com/ProgVal/Limnoria/master/requirements.txt --upgrade
  - sudo pip install git+https://github.com/ProgVal/Limnoria.git@master --upgrade
  - sudo pip install requests

# command to run tests, e.g. python setup.py test
script:
  - echo $TRAVIS_PYTHON_VERSION
  - cd ..
  - mv Limnoria-RealRaum RealRaum
  - supybot-test RealRaum # --no-network --disable-multiprocessing

notifications:
    email: false

matrix:
  fast_finish: true
